BotsAndUsPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.18
  min_vel_x: 0.08

  max_rot_vel:  0.8
  min_rot_vel: -0.8
  min_in_place_vel_theta: 0.2

  acc_lim_x: 1.0
  acc_lim_theta: 0.6

  inscribed_radius: 0.105
  circumscribed_radius: 0.2

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.05
  stopped_rot_vel: 0.01
  stopped_trans_vel: 0.01

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 2.6
  vx_samples: 15
  vth_samples: 20
  sim_granularity: 0.025
  ang_sim_granularity: 0.025
  prune_plan: true

# Waypoint Parameters
  dsample_dist: 0.25 #Distance at which the global plan should be downsampled
  use_p2p: true #If True changes planner behaviour to navigate using Point-to-Point waypoint navigation style
  use_static: true #If True, planner follows only the first global plan generated

# Trajectory Scoring
  heading_scoring: true
  heading_scoring_timestep: 0.8
  path_dist_bias: 0.6
  goal_dist_bias: 0.8
  occdist_scale: 0.01
  look_ahead_dist: 1.0
  oscillation_reset_dist: 0.25
